/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoHandleRouteImport } from './routes/produto.$handle'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoHandleRoute = ProdutoHandleRouteImport.update({
  id: '/produto/$handle',
  path: '/produto/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politicas': typeof PoliticasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/produto/$handle': typeof ProdutoHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politicas': typeof PoliticasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/produto/$handle': typeof ProdutoHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politicas': typeof PoliticasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/produto/$handle': typeof ProdutoHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/politicas'
    | '/produtos'
    | '/sobre'
    | '/produto/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/politicas'
    | '/produtos'
    | '/sobre'
    | '/produto/$handle'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/politicas'
    | '/produtos'
    | '/sobre'
    | '/produto/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PoliticasRoute: typeof PoliticasRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreRoute: typeof SobreRoute
  ProdutoHandleRoute: typeof ProdutoHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$handle': {
      id: '/produto/$handle'
      path: '/produto/$handle'
      fullPath: '/produto/$handle'
      preLoaderRoute: typeof ProdutoHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PoliticasRoute: PoliticasRoute,
  ProdutosRoute: ProdutosRoute,
  SobreRoute: SobreRoute,
  ProdutoHandleRoute: ProdutoHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
